.github/workflows/rust.yml

per #7, aiming to reduce cache eviction due to new cache instances being created every PR / commit.

split ci caching to only update caches from main

---

Cargo.lock
Cargo.toml

since we've dropped bulletproofs as a firmware dependency we don't need the target fix or patch (which no longer exists)...

revert bulletproofs patch to match upstream

---

apdu/src/app_info.rs
fw/.cargo/config.toml
fw/src/consts.rs
fw/src/main.rs
fw/src/ui/menu.rs
lib/src/cli/main.rs
lib/src/error.rs
lib/src/handle.rs
lib/src/lib.rs
lib/src/transport.rs

refactor to support generic transports to simplify the API for consumers
- adds `GenericHandle`, `TransportGeneric`, `LedgerInfo` types generic over underlying transport
- updates `list_devices` to return all devices using filter over available transports
- fixes app info request type, removes old (now unsupported) device info requests

ledger transport refactor

---

Makefile
core/src/engine/event.rs
core/src/engine/function.rs
core/src/engine/mod.rs
core/src/engine/output.rs
core/src/engine/ring.rs
core/src/engine/summary.rs
fw/nanox.json
fw/src/main.rs

attempting to fix the app execution on the nanox (no luck so far)
further improvements to stack frame sizes in the hope that the less efficient ISA caused a recurrence of the 8kb of stack issue, blocking inlining of large functions in the same stack frame and swapping to per-field init of large objects. this doesn't _appear_ to have helped.
testing targets for nanosplus/nanox devices to try and isolate the error from the ISA
- build for nanox with `thumbv7m-none-eabi` target (adds `DIV` and `MOD` instructions), this runs correctly in simulator, @yhql tested this still appears to fail on device
- tested compiling for nanosplus with `thumbv7m-none-eabi` and `thumbv6m-none-eabi` targets, both run fine on the physical nanosplus and simulator, suggesting the issue is specific to the nanox OS / …

stack use improvements (towards nanox execution)

---

fw/src/main.rs
fw/src/ui/approver.rs
fw/src/ui/helpers.rs
fw/src/ui/menu.rs
fw/src/ui/message.rs
fw/src/ui/mod.rs
fw/src/ui/tx_blind_approver.rs
fw/src/ui/tx_summary_approver.rs
lib/src/error.rs
lib/src/tx/mod.rs
lib/tests/helpers.rs
lib/tests/tx.rs

towards #18
- swaps language to `approve` and `reject`
- swaps approve / reject ordering so approve comes first
- improves progress bar rendering slightly (clear syscall vs. rect draw)
- adds arrows to home page
- ensures user lands on home page following pending message

workin' on UI improvements

---

.github/workflows/rust.yml
Makefile

adds folder to firmware packages and renames firmware hex file to match manifest so `ledgerctl install app_nanosplus.json` works as expected

CI - fix fw packages / app names in manifests

---

Cargo.lock
Cargo.toml
apdu/Cargo.toml
apdu/src/helpers.rs
core/Cargo.toml
core/src/engine/function.rs
core/src/engine/ident.rs
core/src/engine/mod.rs
core/src/engine/ring.rs
core/src/engine/summary.rs
fw/.cargo/config.toml
fw/Cargo.lock
fw/Cargo.toml
lib/Cargo.toml
lib/src/handle.rs
tests/Cargo.toml
tests/src/ident.rs

swapped to upstream dalek (from repo) w/ fixes for target selection, serde. some cleanup remaining before this is mergable (propagating errors etc.)
cc. @samdealy, can we remove the `x25519-dalek` patch too?

update to upstream dalek

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
Makefile
apdu/src/digest.rs
apdu/src/lib.rs
apdu/src/tx/summary.rs
core/Cargo.toml
core/build.rs
core/mob.proto
core/src/engine/event.rs
core/src/engine/fog.rs
core/src/engine/function.rs
core/src/engine/mod.rs
core/src/engine/summary.rs
core/src/helpers/mod.rs
core/src/lib.rs
fw/Cargo.lock
fw/Cargo.toml
fw/nanox.json
fw/src/main.rs
fw/src/ui/address.rs
fw/src/ui/app_info.rs
fw/src/ui/menu.rs
fw/src/ui/mod.rs
fw/src/ui/tx_summary_approver.rs
lib/src/tx/summary.rs
tests/Cargo.toml
tests/src/transaction.rs

per #20 
- adds `prost` with a minimal proto file reproducing of `PrintableWrapper` (avoiding grpc components of `mc-api`)
- adds `FogId`s to summary messages as a compressed alternative to fog URLs, removes `ShortAddressHash` as this is now derived on device
- adds helpers for `ShortAddressHash` derivation from primitive types w/ tests against `mc-account-keys` types
- adds helpers for b58 encoding from primitive types w/ tests against `mc-account-keys` types
- updates to new summary reports w/ caching for address resolution
- updates summary view with subpages showing b58 addresses
- replaces key views with b58 encoded address view
this is more alloc heavy than would be ideal, but, cannot currently be avoided due to `prost`. we also can't sign fog authorities at the moment as the CSPRNG …

support b58 addresses' in view and summaries

---

Cargo.lock
lib/Cargo.toml
lib/src/lib.rs
tests/Cargo.toml

updates hidapi to 0.2.2, moves context to `LedgerProvider` to use underlying lazy init of global hidapi context, appears to fix the device unavailable issues on x86 (and has been tested on m1 in prior revisions)
replaces #32, #34

fix for macos device re-enumeration

---

apdu/src/digest.rs
apdu/src/tx/ring.rs
core/src/engine/event.rs
core/src/engine/function.rs
core/src/engine/mod.rs
core/src/engine/ring.rs
core/src/engine/summary.rs
lib/src/tx/ring.rs
tests/src/mlsag.rs

adds `onetime_private_key` to ring init APDU, set from `ring_sign` in library and propagated through to the streaming ring signer context. untested pending vectors with pre-signed inputs.
cc. @christian-oudard

WIP: initial support for pre-signed rings

---

Makefile
apdu/src/state.rs
core/src/engine/digest.rs
core/src/engine/event.rs
core/src/engine/function.rs
core/src/engine/mod.rs
core/src/engine/output.rs
core/src/engine/ring.rs
fw/.gdbinit
fw/Cargo.lock
fw/Cargo.toml
fw/src/main.rs
fw/src/platform.rs
fw/src/ui/menu.rs
fw/src/ui/mod.rs

it turns out the nanox has a more severe stack use limitation, faulting on -memory access- when the stack pointer exceeds 8k, rather than only when invoking syscalls on the nanosplus.
it is expected that this limit will be resolved in future firmware, for now we should be able to avoid the issue by pre-allocating and using out-pointer tricks to avoid rust's lack of working copy elision / NRVO.
following #23, this PR:
- refactors events to be self contained (simplifying passing these by reference)
- moves ui, event, and object storage to the heap w/ pointer-based initialisation
- splits out identity and key image functions so these can no-longer be inlined in `Engine::update`
this reduces our worst-case stack depth by ~2k down to ~7524 bytes which appears to get us under the limit on the …

fix: further stack reductions for nanox support

---

apdu/src/tx/summary.rs
core/src/engine/mod.rs
fw/Cargo.toml
fw/src/main.rs
fw/src/platform.rs
fw/src/ui/menu.rs
fw/src/ui/mod.rs
fw/src/ui/settings.rs

this changes the b58 encoded address displayed on the device, and defaults to the mobilecoin mainnet fog. 
NVM backed persistence is gated behind the `nvm` feature due to crashes on both the nanosplus and speculos (under investigation), so for the moment this does not persist between app launches.
resolves #42

Add settings page for fog selection

---

core/src/engine/mod.rs

allow new identity signing requests from both the init and signed states and revert to signed state following completed ident request.
cc. @holtzman

fix engine ident function states

---

core/src/helpers/mod.rs

add eUSD token string (probably also worth fixing upstream `TokenId` to allow const construction)
cc. @holtzman

add eUSD token format to transaction display

---

fw/src/ui/mod.rs
fw/src/ui/progress.rs

progress bar render now only clears the screen on the first call, resolves flickering when progress bar updates.
Co-authored-by: Henry Holtzman <henry@mobilecoin.com>
cc. @holtzman

fix progress bar rendering / flickering

---

fw/src/consts.rs
fw/src/main.rs
fw/src/platform.rs

it is unclear what expectations ledger live has as to APDUs and responses, the standard app and device info objects do not seem to be enough... this is however a useful step towards #19

improvements to standard messages for ledger live interaction

---

fw/Cargo.lock
fw/Cargo.toml

this has no firmware impact as is only used for generating a build time in `fw/build.rs`.
resolves:
- https://github.com/mobilecoinofficial/ledger-mob/security/dependabot/7
- https://github.com/mobilecoinofficial/ledger-mob/security/dependabot/8
removing this from non-fw components also requires upstream dependency updates

update chrono / time packages used in fw/build.rs

---

Cargo.lock
Makefile
README.md
core/src/engine/function.rs
core/src/engine/mod.rs
core/src/engine/ring.rs
core/src/engine/summary.rs
core/src/helpers/mod.rs
fw/Cargo.lock

adds `make miri` which runs miri tests on `core` functions that use out-pointers. requires `cargo-nextest` and patching the vendored `mc-crypto-hashes` to disable `simd` (and takes -forever- to run, so is not a reasonable candidate for CI).
also reverts a transmute trick to save on stack frame use that miri was unhappy with, though this is _valid_ i am not sure how to convince miri of such, and we currently have the stack headroom for this to be an acceptable compromise (tested on the physical nanosplus).

add support for miri-based testing of functionality using out-pointers

---

core/src/engine/mod.rs
fw/Cargo.lock
fw/Cargo.toml
fw/build.rs
fw/src/main.rs
fw/src/platform.rs
fw/src/ui/progress.rs

based on an example from the discord, @yhql this seems to crash when the syscall is executed (also, `os_ux_blocking` is declared in rust but has no matching symbol when linking)

swap from exit to pin validation on timeout

---

core/src/engine/mod.rs

as it's a one-off operation (rather than a streaming one) we do not need to persist an error on the device.

remove unneeded error state on ident failure 

---

fw/Cargo.lock
fw/Cargo.toml
fw/src/main.rs
fw/src/platform.rs

the normal function of the RNG is critical to the operation of the app, while bolos function calls in the past have moved resulting in failures when accessing the RNG.
to mitigate this risk we run some simple RNG tests at initialisation time, not to prove the RNG is -correct- but to ensure that calls through the OS behave as expected.
platform RNG tests now check both `LedgerRng` and injected `OsRng` instances using nist monobit and block frequency statistical tests.

improve testing of RNG syscalls

---

fw/src/main.rs

fixes delay between pin unlock and menu re-rendering

Force re-draw on pin entry

---

.github/workflows/rust.yml
Makefile
README.md
apdu/src/digest.rs
apdu/src/ident.rs
apdu/src/lib.rs
apdu/src/state.rs
apdu/src/tx/mod.rs
apdu/src/tx/summary.rs
core/src/engine/error.rs
core/src/engine/function.rs
core/src/engine/output.rs
core/src/engine/summary.rs
core/src/lib.rs
docs/apdu.md
fw/docs/apdu.md
lib/src/handle.rs
tests/src/lib.rs

- fix APDU rustdoc links from core
- add missing summary steps, encoding diagrams
- move `fw/docs/apdu.md` to `docs/apdu.md`, update with links to rustdocs.

improve apdu documentation

---

Cargo.lock
apdu/Cargo.toml
core/Cargo.toml
core/src/engine/summary.rs
fw/Cargo.lock
fw/Cargo.toml
fw/src/ui/tx_summary_approver.rs
lib/Cargo.toml
tests/Cargo.toml

updates to mobilecoin.git v5.0, using updated transaction report implementation (https://github.com/mobilecoinfoundation/mobilecoin/pull/3316) with patch for ledger required MSRV.
replaces #63

update to mobilecoin v5.0 release
